language: objective-c
before_install:
- MODULE_ROOT=$PWD
install:
- mkdir -p $HOME/Library/Application\ Support/Titanium/
- wget http://builds.appcelerator.com/mobile/3.4.0/mobilesdk-3.4.0.GA-osx.zip -O $HOME/Library/Application\
  Support/Titanium/mobilesdk-3.4.0.GA-osx.zip
- cd $HOME/Library/Application\ Support/Titanium/
- unzip -o mobilesdk-3.4.0.GA-osx.zip
before_script:
- cd $MODULE_ROOT
script:
- cd ./iphone/
- ./build.py
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NhzPsm6tkcZNc7RPMwASH1D5xlbHfRaC4ssBBsC1MG5NOML9rE7wFPtag9Q6wQzCEZcAsCFIT3cktdQYOVGE7wgb7TUox7nhu+1C2+tymVozNFuhaiZ4mW4LpYTT82FgCXq81/bHiHpxj82T0f2V3XwNQ0tdEw5EwA7SlqEuKd4=
  file: 'iphone/uk.co.tbp.pushio-iphone-1.1.1.zip'
  on:
    all_branches: true
    tags: true
