language: objective-c
env:
 global:
   - "MODULE_NAME=uk.co.tbp.pushio" 
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - curl -o settup.sh https://raw.githubusercontent.com/TheBookPeople/ci-scripts/master/travis/titanium/modules/settup.sh
    - source settup.sh -s "3.4.1.GA"
script: 
    - curl -o build.sh https://raw.githubusercontent.com/TheBookPeople/ci-scripts/master/travis/titanium/modules/build.sh
    - source build.sh
before_deploy:
  - export ANDROID_DIST=$(find .  -name 'uk.co.tbp.pushio-android-*.zip)
  - export IOS_DIST=$(find .  -name 'uk.co.tbp.pushio-ios-*.zip)
  - echo "deploying Android $ANDROID_DIST to GitHub releases"
  - echo "deploying iOS $IOS_DIST to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NhzPsm6tkcZNc7RPMwASH1D5xlbHfRaC4ssBBsC1MG5NOML9rE7wFPtag9Q6wQzCEZcAsCFIT3cktdQYOVGE7wgb7TUox7nhu+1C2+tymVozNFuhaiZ4mW4LpYTT82FgCXq81/bHiHpxj82T0f2V3XwNQ0tdEw5EwA7SlqEuKd4=
  file_glob: true
  file:
    - "${ANDROID_DIST}"
    - "${IOS_DIST}"
  on:
    all_branches: true
