markdown: kramdown
highlighter: pygments
relative_permalinks: true
url: //thebookpeople.github.io/titanium-pushio
repository: https://github.com/TheBookPeople/titanium-pushio 
collections:
  docs:
    output: true
